version: "3.4"

networks:
  nats-net:
    external: true

x-volumes:
  &project-home-dir
    .:/src

x-volumes:
  &web-vol
  - *project-home-dir

services:
  userserver:
    image: micro_userserver:latest
    restart: always
    networks:
      - nats-net

  imserver:
    image: micro_imserver:latest
    restart: always
    networks:
      - nats-net
  
  websocket:
    image: micro_websocket:latest
    restart: always
    networks:
      - nats-net 

  uploadserver:
    image: micro_uploadserver:latest
    ports:
      - "8086:8086"
    restart: always
    networks:
      - nats-net

  web:
    image: micro_gateway:latest
    ports:
      - "8081:8081"
    volumes: *web-vol
    restart: always
    depends_on:
      - userserver
      - imserver
    networks:
      - nats-net
