FROM golang

WORKDIR /src
COPY go.mod /src
COPY go.sum /src

ENV GOPROXY https://goproxy.cn,direct

RUN go mod download

COPY . .

CMD go run /src/imserver/cmd/rpcproducer/im_rpc.go -f /src/imserver/cmd/config/config_rpc.json